# Generated by Django 3.2.5 on 2021-07-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_zip', models.IntegerField(blank=True, null=True)),
                ('address_flat', models.CharField(blank=True, max_length=50, null=True)),
                ('address_area', models.CharField(blank=True, max_length=50, null=True)),
                ('address_landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('address_state', models.CharField(blank=True, max_length=50, null=True)),
                ('address_type', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountExtention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_verification_link', models.TextField(blank=True, null=True)),
                ('token_email', models.CharField(blank=True, max_length=200, null=True)),
                ('token_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('changepass_uid', models.CharField(blank=True, max_length=200, null=True)),
                ('email_is_verified', models.BooleanField(default=False)),
                ('phone_is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
