# Generated by Django 3.2.5 on 2021-07-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountextention',
            name='permission',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff'), ('superuser', 'Superuser')], default='User', max_length=20, null=True),
        ),
    ]
