# Generated by Django 3.2.5 on 2021-08-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_info',
            new_name='paymentInfo',
        ),
    ]
