# Generated by Django 3.2.5 on 2021-07-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ornamentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=250, null=True)),
                ('image_url', models.ImageField(default='', upload_to='orders/images')),
                ('metal_choice', models.CharField(choices=[('yellow_gold', 'Yellow-Gold'), ('rose_gold', 'Rose-Gold'), ('white_gold', 'White-Gold'), ('silver', 'Silver')], max_length=20, null=True)),
                ('gold_quality', models.CharField(blank=True, choices=[('14k', '14k'), ('18k', '18k')], max_length=20)),
                ('quantity', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20)),
                ('budget', models.CharField(blank=True, max_length=20, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('order_status', models.CharField(choices=[('recieved', 'Recieved'), ('verified', 'Verified'), ('started', 'Started making'), ('almost', 'Almost completed'), ('complete', 'Completed making')], default='Recieved', max_length=20, null=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
