# Generated by Django 3.2.5 on 2021-08-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ornamentorder_design_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ornamentorder',
            name='design_insight',
            field=models.CharField(blank=True, choices=[('I have image of exactly what I want', '1'), ('I have some images and knowledge of what I want to make', '2'), ('I have some general ideas', '3'), ('I have no idea, need help!', '4')], max_length=100),
        ),
    ]
