# Generated by Django 3.2.5 on 2021-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ornamentorder_design_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='ornamentorder',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ornamentorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
