# Generated by Django 3.2.5 on 2021-08-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210818_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='ornamentorder',
            name='updated_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
