# Generated by Django 3.2.5 on 2021-08-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ornamentorder_updated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ornamentorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
